
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/anon/.tea/cmake.org/v3.27.3/var/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.90.1-microsoft-standard-WSL2 - x86_64
...
